### ISSUE TITLE
Almost all blocks except loose ore block have an unnecessary line breaks in info

### ISSUE THREAD

**Issue by kousakak** [anegostudios/VintageStory-Issues#1241]
**Game Version:** 1.15.3
**Platform:** Windows  
**Modded:** No

### Description
Almost all blocks except loose ore block have an unnecessary line breaks in info
Same issure on all kinds of loose ore blocks was fixed in 1.15.0

### Screenshots
![2021-07-19_09-23-23](https://user-images.githubusercontent.com/60339803/127819655-3e56e87f-35cb-4d16-a64d-30c3ae549bd4.png)

**Comment by Craluminum2413** [comment]
I thought that it was done to insert the name of the mod from which the block is

**Comment by tyronx** [comment]
Thanks, this should be fixed next release

**Comment by kousakak** [comment]
> Thanks, this should be fixed next release

Sorry to disturb but same issure still exist in 1.15.5 on all kinds of stone and ore,wood logs include bamboo and dry stone,between block name and description

**Comment by Craluminum2413** [comment]
Assume fixed
