### ISSUE TITLE
Can't add honey from buckets to meal

### ISSUE THREAD

**Issue by Dashutka1** [anegostudios/VintageStory-Issues#1598]
Game Version: 1.16.0
Platform: Windows
Modded: No
Singleplayer

I can not do jam, I can't add honey to porridge or meat stew. I added honey in different ways, watched videos on YouTube, how others make jam. Strictly followed the recipe from the video and still does not work. Please fix honey recipes. It can be eaten, but should not be added to dishes. Porridge or jam is simply impossible to cook with honey.

**Comment by copygirl** [comment]
May I ask why you closed this?

**Comment by Dashutka1** [comment]
> Могу я спросить, почему вы закрыли это?
Because I solved the problem. It turns out that for jam or
meat stew in a pot, honey should be put from a bowl, not from a bucket. Each berry requires 0.2 liters of honey.

**Comment by copygirl** [comment]
I see. Thank you.

**Comment by copygirl** [comment]
I'm going to re-open this. Buckets with honey should work when adding honey to meals.

There is the possibility this is fixed in the 1.16.1 release candidates, but I don't have the time to check myself.

**Comment by svanheulen** [comment]
This is still happening in 1.16.4-rc1, but I don't think it's really a bug so much as a quality of life shortfall.
You can only add/remove liquid that amounts to 1/10th of the container size. So buckets do 1 liter, jugs do 0.3 liters, and bowls do 0.1 liter. It would make sense to have a ctrl or shift click allow you to add/remove smaller or larger amounts.

**Comment by Craluminum2413** [comment]
1L of honey is added when using bucket
