### ISSUE TITLE
Freezing effect does not go away after warming

### ISSUE THREAD

**Issue by bluelightning32** [anegostudios/VintageStory-Issues#2135]
**Game Version:** 1.17.0-rc.7
**Platform:** Linux
**Modded:** Yes, lots

**SP/MP:** Multiplayer

### Description
The freezing effect started getting applied on my character during winter. However, going inside near a fire does not make it go away, even when the body temperature is 37.8. More specifically the icicles keep fading in and out and shivering occurs.

### How to reproduce
1. Log into a server where it's winter
2. Wait for character to get cold and show the freezing effect.
3. Get warm.
4. Observe that freezing effect does not go away.
5. Logging out and back in temporarily makes the effect go away.

### Expected behavior
Freezing effect should disappear when body temperature rises.

### Screenshots
![image](https://user-images.githubusercontent.com/21202621/187032251-8c9756fb-838d-432c-b3e4-1c942cede369.png)

### Logs
I didn't find anything relevant in the logs.

**Comment by tyronx** [comment]
Hey, is this a world with a non default worldheight (256)? If so it should be fixed next release

**Comment by bluelightning32** [comment]
The world height is default. Also I tested with rc8, and the problem is not fixed.

**Comment by tyronx** [comment]
i'm not able to reproduce this in single player without mods

**Comment by bluelightning32** [comment]
After removing all of the mods on my server, it still reproduces with 1.17.0 (final).
![image](https://user-images.githubusercontent.com/21202621/187845725-f0e7bc53-06fd-4bc4-b401-8dc376245f88.png)

It only happens when the outside temperature is cold. It seems that the freezing effect logic is independent from the current body temperature, and the freezing effect uses the outside temperature instead of the room temperature.

To repro, advance the calendar to winter time, but go inside a room to stay warm. Alternate between advancing the clock forward 6 hours twice and sleeping. After one or two cycles, the freezing bug occurs.

**Comment by tyronx** [comment]
thanks for the report, should be fixed 1.17.1
