### ISSUE TITLE
Crash after world fails to load

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#297]
Occurs after #296 or (in some cases?) when clicking "Cancel" as the world is loading.

```
Version: v1.9.3 (Stable)5/15/2019 10:07:10 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object
  at Vintagestory.Client.SystemRenderDecals.Dispose (Vintagestory.Client.ClientMain game) [0x00001] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/Systems/Render/RenderDecals.cs:439 
  at Vintagestory.Client.ClientMain.Dispose () [0x00019] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/ClientMain.cs:2845 
  at Vintagestory.Client.ClientMain.DestroyGameSession (System.Boolean gotDisconnected) [0x00186] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/ClientMain.cs:2775 
  at Vintagestory.Client.GuiScreenConnectingToServer.OnCancel () [0x0000f] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/MainMenu/Screens/GuiScreenConnectingToServer.cs:186 
  at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement (Vintagestory.API.Client.ICoreClientAPI api, Vintagestory.API.Client.MouseEvent args) [0x0005e] in /home/copygirl/projects/VintageStory/game/VintagestoryApi/Client/UI/Elements/Impl/Interactive/Controls/GuiElementTextButton.cs:234 
  at Vintagestory.API.Client.GuiElement.OnMouseUp (Vintagestory.API.Client.ICoreClientAPI api, Vintagestory.API.Client.MouseEvent args) [0x00018] in /home/copygirl/projects/VintageStory/game/VintagestoryApi/Client/UI/Elements/Impl/GuiElement.cs:639 
  at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp (Vintagestory.API.Client.ICoreClientAPI api, Vintagestory.API.Client.MouseEvent args) [0x00001] in /home/copygirl/projects/VintageStory/game/VintagestoryApi/Client/UI/Elements/Impl/Interactive/Controls/GuiElementTextButton.cs:220 
  at Vintagestory.API.Client.GuiComposer.OnMouseUp (Vintagestory.API.Client.MouseEvent mouse) [0x0001e] in /home/copygirl/projects/VintageStory/game/VintagestoryApi/Client/UI/GuiComposer.cs:366 
  at GuiScreen.OnMouseUp (Vintagestory.API.Client.MouseEvent e) [0x00039] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/MainMenu/Screens/Special/GuiScreen.cs:158 
  at Vintagestory.Client.ScreenManager.OnMouseUp (Vintagestory.API.Client.MouseEvent e) [0x0000e] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/ScreenManager.cs:716 
  at Vintagestory.Client.ClientPlatformWindows.Mouse_ButtonUp (System.Object sender, OpenTK.Input.MouseButtonEventArgs e) [0x00031] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/ClientPlatform/Input.cs:240 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.MouseButtonEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.MouseButtonEventArgs)
  at OpenTK.NativeWindow.OnMouseUp (OpenTK.Input.MouseButtonEventArgs e) [0x00000] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at OpenTK.NativeWindow.OnMouseUpInternal (System.Object sender, OpenTK.Input.MouseButtonEventArgs e) [0x00000] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.MouseButtonEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.MouseButtonEventArgs)
  at OpenTK.Platform.NativeWindowBase.OnMouseUp (OpenTK.Input.MouseButton button) [0x0002e] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at OpenTK.Platform.X11.X11GLNative.ProcessEvents () [0x008e3] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at OpenTK.NativeWindow.ProcessEvents (System.Boolean retainEvents) [0x00035] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at OpenTK.NativeWindow.ProcessEvents () [0x00000] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x000da] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <d2cd3fbe958341e98eff3ee31a301de2>:0 
  at Vintagestory.Client.Program.Start (Vintagestory.Client.ClientProgramArgs args, System.String[] rawArgs) [0x00337] in /home/copygirl/projects/VintageStory/game/VintagestoryClient/Program.cs:285 
  at Vintagestory.Client.Program+<>c__DisplayClass11_0.<.ctor>b__0 () [0x00001] in /home/copygirl/projects/VintageStory/game/VintagestoryClient/Program.cs:168 
  at Vintagestory.ClientNative.CrashReporter.Start (System.Threading.ThreadStart start) [0x0002a] in /home/copygirl/projects/VintageStory/game/VintagestoryLib/Client/ClientPlatform/ClientNative/CrashReporter.cs:96 
  at Vintagestory.Client.Program..ctor (System.String[] rawArgs) [0x001a3] in /home/copygirl/projects/VintageStory/game/VintagestoryClient/Program.cs:168 
  at Vintagestory.Client.Program.Main (System.String[] rawArgs) [0x000b1] in /home/copygirl/projects/VintageStory/game/VintagestoryClient/Program.cs:69 
-------------------------------
```

**Comment by tyronx** [comment]
I assume this is fixed with the fix of #296

**Comment by copygirl** [comment]
This still happens when clicking "Cancel" before the world is loaded or so.

**Comment by tyronx** [comment]
Right. I just found the bug this morning and fixed it, so closing again :D

**Comment by copygirl** [comment]
Pff, fine!
