### ISSUE TITLE
Spooktober : crash when chiseling a pumpkin

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3124]
### Game Version

1.18.12

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

As we are in October IRL, I tried to chisel pumpkins. The game soon crash, after removing or adding a few voxels, or when adding the glowing material. Crash in MP and creative SP.

### How to reproduce

Place a pumpkin on the ground, take hammer and chisel and start chiseling. Game will soon crash.

### Logs

```Running on 64 bit Linux with 15936 MB RAM
Game Version: v1.18.12 (Stable)
10/1/2023 12:59:29 PM: Critical error occurred
Loaded Mods: game@1.18.12, creative@1.18.12, survival@1.18.12
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityChisel.SetVoxel(Vec3i voxelPos, Boolean add, IPlayer byPlayer, Byte materialId) in VSSurvivalMod\Systems\Microblock\BEChisel.cs:line 255
   at Vintagestory.GameContent.BlockEntityChisel.UpdateVoxel(IPlayer byPlayer, ItemSlot itemslot, Vec3i voxelPos, BlockFacing facing, Boolean isBreak) in VSSurvivalMod\Systems\Microblock\BEChisel.cs:line 153
   at Vintagestory.GameContent.ItemChisel.OnBlockInteract(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, Boolean isBreak, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemChisel.cs:line 325
   at Vintagestory.GameContent.ItemChisel.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemChisel.cs:line 236
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 834
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Saricane** [comment]
It would be great if this particularly bug could be fixed before Nov 30, so we don't have to wait another complete IRL year to chisel pumpkins.

**Comment by DejFidOFF** [comment]
Confirming too. Windows 10. And gr8 3x crashes in live stream when I trying to show audience  chiseled glowing pumpkin .

**Comment by Saricane** [comment]
DejFidOFF, if you have both client and server on 1.18.15, and use newly generated pumpkins with 1.18.15, this bug is fixed. Drop your 1.18.14 (and less) pumpkins.

**Comment by DejFidOFF** [comment]
No, it´s not fixed. Everytime i try to chisel glowblock at pumpkin, game crash.

Running on 64 bit Windows with 65493 MB RAM
Game Version: v1.18.15 (Stable)
31.10.2023 16:42:39: Critical error occurred
Loaded Mods: acorns@0.5.2, aculinaryartillery@1.0.15, bettercrates@1.6.0, betterruins@0.2.4, Ceramos@0.4.2, chiseltools@1.9.2, drdecor@1.2.0, extrachests@1.7.0, fantasycreatures@0.6.2, capreolinae@1.0.4, foundrymod@1.0.0, furniturelibrary@1.0.9, giantgouramis@1.0.1, instruments@1.2.2, millwright@1.1.0, moreicons_cs@1.1.0, peacockbasses@1.1.1, primitivesurvival@3.3.0, spyglass@0.4.5, tprunes@1.1.0, thecritterpack@0.7.6, translocatorengineeringredux@1.4.7, truesunfishes@1.1.1, game@1.18.15, ancienttools@1.5.9, betterfirepit@1.1.1, betterjonasdevices@1.0.1, canbeignited@1.1.0, carryon@1.0.0, commonlib@2.2.0, expandedfoods@1.6.8, fishing@1.1.5, fromgoldencombs@1.4.21, fsmlib@0.1.8, glidervar@1.1.1, hudclock@3.3.0, sailboat@1.1.0, medievalexpansion@3.11.1, morepiles@1.4.3, petai@1.8.1, simplestep@1.0.8, stonebakeoven@1.1.0, th3dungeon@0.2.0, usefulstuff17@1.1.6, vinconomy@0.1.3, creative@1.18.15, vsquest@0.5.0, survival@1.18.15, workbenchexpansion@1.7.0, xlib@0.7.4, awearablelight@1.0.8, betterbamboo@1.0.2, bugnetcompatibility@1.0.1, captureanimals@2.5.3, cob@1.5.2, em@2.4.1, maltiezfirearms@0.3.2, playercorpse@1.8.0, rifteye@0.2.4, stonequarry@3.1.7, wolftaming@1.8.0, xskills@0.7.5, bricklayers@2.4.0, vsvillagecob@0.1.4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityChisel.SetVoxel(Vec3i voxelPos, Boolean add, IPlayer byPlayer, Byte materialId) in VSSurvivalMod\Systems\Microblock\BEChisel.cs:line 255
   at VSSurvivalMod.Systems.ChiselModes.ChiselMode.Apply(BlockEntityChisel chiselEntity, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean isBreak, Byte currentMaterialIndex) in VSSurvivalMod\Systems\Microblock\ChiselMode\ChiselMode.cs:line 49
   at Vintagestory.GameContent.BlockEntityChisel.UpdateVoxel(IPlayer byPlayer, ItemSlot itemslot, Vec3i voxelPos, BlockFacing facing, Boolean isBreak) in VSSurvivalMod\Systems\Microblock\BEChisel.cs:line 114
   at Vintagestory.GameContent.BlockEntityChisel.OnBlockInteract(IPlayer byPlayer, BlockSelection blockSel, Boolean isBreak) in VSSurvivalMod\Systems\Microblock\BEChisel.cs:line 102
   at Vintagestory.GameContent.ItemChisel.OnBlockInteract(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, Boolean isBreak, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemChisel.cs:line 322
   at Vintagestory.GameContent.ItemChisel.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemChisel.cs:line 236
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, Boolean firstEvent, EnumHandHandling& handling) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1007
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 834
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 31.10.2023 16:30:53, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.18.15.0, časové razítko: 0x64e841c5
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x6a08
Čas spuštění chybující aplikace: 0x01da0c0f25707071
Cesta k chybující aplikaci: D:\games\Vintagestory\Vintagestory.exe
Cesta k chybujícímu modulu: D:\games\Vintagestory\Lib\openal32.dll
ID zprávy: be27c01f-4e75-4102-8bac-f6344f127023
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 29.10.2023 19:46:32, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.18.15.0, časové razítko: 0x64e841c5
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x5ff4
Čas spuštění chybující aplikace: 0x01da0a96e06faca2
Cesta k chybující aplikaci: D:\games\Vintagestory\Vintagestory.exe
Cesta k chybujícímu modulu: D:\games\Vintagestory\Lib\openal32.dll
ID zprávy: a371dc31-4d01-44bf-951d-6036aa20d217
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 29.10.2023 17:38:10, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.18.15.0, časové razítko: 0x64e841c5
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x2db0
Čas spuštění chybující aplikace: 0x01da0a85f7250223
Cesta k chybující aplikaci: D:\games\Vintagestory\Vintagestory.exe
Cesta k chybujícímu modulu: D:\games\Vintagestory\Lib\openal32.dll
ID zprávy: 558d99ee-2771-460d-bbb4-e2712cd9ef29
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }

**Comment by Saricane** [comment]
You report a bug with dozens of mods active. Bug report must be done with vanilla. Since both the server and the client had been updated to 1.18.15, I carve everyday dozens of pumpkins (I farm them to have a huge stock till next year) without a single crash.

**Comment by DejFidOFF** [comment]
> You report a bug with dozens of mods active. Bug report must be done with vanilla. Since both the server and the client had been updated to 1.18.15, I carve everyday dozens of pumpkins (I farm them to have a huge stock till next year) without a single crash.

You are right. Vanilla game have no issues with carving pumpkins. That dozens mods active is because I am at SMP and unfortunately no chance to disable any of them.
