### ISSUE TITLE
Not possible to grant other users proper access (use and place) to multiplayer land claim

### ISSUE THREAD

**Issue by zkol** [anegostudios/VintageStory-Issues#316]
**Game Version:** 1.9.7 Multiplayer
**Platform:** Linux (Ubuntu 18.4. LTS with mono 5.20.1.19)
**Modded:** No

This issue was mentioned for 1.9.4 on discord, but  I found no development reaction and no existing bug report, so I retested for 1.9.7 and filed a proper report at least for documentation purpose.

### Description
Following all given instructions (wiki, in game), it seems to be impossible to grant other users proper access (use and place blocks) to a land claim on multiplayer. Of course it is possible to grant rights to **either use** (e.g. grant use to place a pot in a fireplace, cook the meal, pick the pot) **or place** blocks (e.g. place the pot on the ground in order to fill a bowl). It seems to be impossible to combine theses privileges.

### How to reproduce
1. Make a land claim and save it
2. Make other player ("dude") visit the land land claim for testing
3. Player dude tests opening a chest and placing a torch 
(both does not work as expected)
4. Grant "all" to player dude
- /land claim load
- /land claim grant dude all
- /land claim save
5. Player dude can now  place a torch :-) but not open a chest :-(
6. Grant "use" to player dude
- /land claim load
- /land claim grant dude use
- /land claim save
7. Player dude can now open a chest :-) but cannot place a torch any more :-(
8. Grant "all" and "use" to player dude
- /land claim load
- /land claim grant dude all use
- /land claim save
9. Result is same as 4.

### Expected behavior
Expected is to have a documented way to grant both aspects to a user (whatever way this is).
 
Most intuitive solution is that "all" **includes** the the right to use. 
The second most intuitive solution is that the consecutively granted rights are **combined** (means a sequence of all and use results in both rights). 
The third most intuitive solution is that the grant command considers **both** rights given as parameters (all **and** use) and not only the first.

**Comment by copygirl** [comment]
Likely found the issue: As you might be able to tell by testing, there's two separate access flags: `Use` and `BuildOrBreak`. The command is likely supposed to give both when you type `all`, but it incorrectly only applied the latter. I submitted a merge request to fix this.

**Comment by copygirl** [comment]
Done :+1:

**Comment by zkol** [comment]
Retested with 1.9.9: 
* grant use works as expected (privilege to use items, e.g open a chest, no privilege to place/break blocks, e.g. placing a torch)
* grant all still does not work as expected, but inverted to the previous situation: no privilege to break/place blocks, but privilege to use item.
Obviously the fix did not work, please reopen!

**Comment by copygirl** [comment]
It appears to work for me. Did you run `/land claim save`?

**Comment by zkol** [comment]
Yes I granted again and saved as well (repeating the initial test). Breaking/Placing Blocks was not possible with "all". But I used the same existing land claim and the same player as in the first test. I will try to revoke previous grants and then grant again.

**Comment by zkol** [comment]
Well, I tried several things on Chromtech (Client 1.9.9, Server meanwhile 1.9.10)

- Reusing the existing land claim (claim id 0), I revoked all grants and granted "all" as described in the OP: Dude is only able to use but not to break blocks.
- First try to free the land, in order to claim and grant from scratch:
/land claim load
/land free 0 confirm
/land claim save
This had no affect, the land claim persisted without modification
- Second try to free the land, in order to claim and grant from scratch:
/land free 0 confirm
This produced an inconsistency message: "Incorrect state. Spatially partitioned claim list not consistent with full claim list. Please contact the game  developer. A Server restart may temporarily fix the issue." 
For me (player skol) the land claim was removed (even after re-login), but for player dude the claim still persists (with grants working as described above). We will see how this will work after server restart.

- Third try to claim and grant from scratch:
claimed another piece of land, and before saving:
/land claim grant dude all
/land claim save
This seems to work as expected, player dude can break blocks.

**Comment by tyronx** [comment]
> "Incorrect state. Spatially partitioned claim list not consistent with full claim list. Please contact the game developer. A Server restart may temporarily fix the issue."

I'd love to know how to reproduce this as well.

**Comment by tyronx** [comment]
Is this still a thing as of v1.10.7?

**Comment by copygirl** [comment]
Closing since we could not reproduce the issue and @zkol didn't respond.
