### ISSUE TITLE
Map only records when minimap is open

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#3160]
### Game Version

1.18.15

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When you travel around, the world map records your surroundings - but only if the minmap is enabled. If you have no minimap, the world map won't grow as you explore.

### How to reproduce

1. Join a world you haven't explored
2. Make sure the minimap is disabled
3. Look at the map and check your coordinates
4. Travel in any direction for a while, until the world map *should* have recorded a larger area
5. Open the world map and observe that your previous location has become unmapped

### Screenshots

![Screenshot at 2023-10-17 08-12-09](https://github.com/anegostudios/VintageStory-Issues/assets/19580483/1333438a-2c10-425e-8c21-9d0b8f4b9cce)
Traveled south from spawn on a new world. Initially the minimap was enabled, then it was disabled for a while, then it was enabled again. No teleportation was used - the blank space in between was travelled through normally, the only difference is the minimap was disabled during transit.

### Logs

```Log```

**Comment by sekelsta** [comment]
On further inspection, leaving the minimap open doesn't reliably avoid this, but does still seem to help.

**Comment by EnigmaticaGH** [comment]
Looks like it's because your view distance is too low. Increase view distance to more than one chunk and it should fix itself. The map only records the chunks that get fully loaded. If view distance is too low, the minimap might not realize that chunk is loaded in and not record it.

**Comment by Ragolution** [comment]
Couldn't reproduce on Windows using given parameters, even with very low view distance. Yes, I'm aware you put your OS as Linux for this issue.

**Comment by sekelsta** [comment]
Issue persists after increasing view distance from 64 to 256. Minimap was on briefly at spawn, then off the rest of the time. The recorded areas are exactly and only the places where I stopped to view the world map. Where I did not open the map, even if I stopped and stayed still a while, nothing was recorded.
![Screenshot at 2023-10-24 17-34-48](https://github.com/anegostudios/VintageStory-Issues/assets/19580483/7e64f049-faa2-4089-baa3-7440dc94179b)
Will try and see if I can get a repro on Windows when I get a chance.

**Comment by sekelsta** [comment]
Issue also occurs on 1.20-pre.5.
