### ISSUE TITLE
Block Texture Bug

### ISSUE THREAD

**Issue by WickedBuzzard** [anegostudios/VintageStory-Issues#3633]
### Game Version

v1.19.4-rc2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Screenshots

![2024-02-25_17-18-17](https://github.com/anegostudios/VintageStory-Issues/assets/161125142/14f305fb-f7cb-437e-822c-10eaa310c9a3)

### Logs

```Log```

**Comment by radfast** [comment]
Thanks for the report, this is a concern ... we thought all these issues with ruins were fixed!

Is this a new 1.19.4-rc.2 world, or a world generated in an earlier game version and you are now playing it in 1.19.4-rc.2 (so maybe this position was generated already a while back in an earlier game version?)

Please can you look directly at one of these bugged blocks, press Ctrl+F3 to show debug info and fps graph, and take a screenshot and post it here?

**Comment by WickedBuzzard** [comment]
This is a new generated 1.19.4-rc.2 world. 
![2024-02-26_16-48-19](https://github.com/anegostudios/VintageStory-Issues/assets/161125142/8e4da226-944d-4199-8b31-692e0cb5cf02)

**Comment by WickedBuzzard** [comment]
1.19.4-rc.3 world still exists
![2024-02-26_16-55-27](https://github.com/anegostudios/VintageStory-Issues/assets/161125142/b4df4d5b-966a-48e2-bcfa-aecaa6692848)

**Comment by Craluminum2413** [comment]
Closing due to inactivity
