### ISSUE TITLE
Exception thrown during handling event OnWorldgenStartup

### ISSUE THREAD

**Issue by tkk2112** [anegostudios/VintageStory-Issues#3752]
### Game Version

v1.19.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

The save was started with mods, but the save crashes the server or local game with or without mods when trying to load, see log section.

I can upload the save somewhere if needed.

### Logs

26.3.2024 10:42:27 [Event] Starting world generators...
26.3.2024 10:42:29 [Notification] Sending server identification with remap False.  Server control privilege is True
26.3.2024 10:42:46 [Notification] Reloaded 35 tree generators
26.3.2024 10:42:46 [Event] Loading 7x7x8 spawn chunks...
26.3.2024 10:42:46 [Event] 0% (49 in queue)
26.3.2024 10:42:46 [Error] Failed deserializing a map region. Not in repair mode, will exit.
26.3.2024 10:42:46 [Error] Exception thrown during handling event OnWorldgenStartup:
26.3.2024 10:42:46 [Error] Exception: Sub-message not read correctly
   at ProtoBuf.ProtoReader.EndSubItem(SubItemToken token, ProtoReader reader) in C:\Code\pb-net_24\src\protobuf-net\ProtoReader.cs:line 618
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type) in C:\Code\pb-net_24\src\protobuf-net\ProtoReader.cs:line 592
   at proto_60(Object, ProtoReader)
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at Vintagestory.API.Util.SerializerUtil.Deserialize[T](Byte[] data)
   at Vintagestory.Server.ServerMapRegion.FromBytes(Byte[] serializedMapRegion)
   at Vintagestory.Server.ServerSystemSupplyChunks.TryLoadMapRegion(Int32 regionX, Int32 regionZ)
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegion(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams)
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegionEnsureNeighbours(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams)
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapChunk(ChunkColumnLoadRequest chunkRequest, Boolean forceCreate)
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn_OnChunkThread(ChunkColumnLoadRequest chunkRequest, Int32 stage)
   at Vintagestory.Server.ServerSystemSupplyChunks.loadChunkAreaBlocking(Int32 chunkX1, Int32 chunkZ1, Int32 chunkX2, Int32 chunkZ2, Boolean isStartupLoad, ITreeAttribute chunkGenParams)
   at Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks()
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldgenStartup()
   at Vintagestory.Server.ServerEventManager.TriggerWorldgenStartup()
26.3.2024 10:42:46 [Event] Begin game ticking...
26.3.2024 10:42:46 [Notification] Entering runphase RunGame
26.3.2024 10:42:46 [Notification] Successfully loaded 89 waypoints
26.3.2024 10:42:46 [Notification] Starting server threads
26.3.2024 10:42:46 [Event] Singleplayer Server now running!
26.3.2024 10:42:46 [Error] Failed deserializing a map region. Not in repair mode, will exit.
26.3.2024 10:42:46 [Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
26.3.2024 10:42:46 [Error] Exception: Sub-message not read correctly
   at ProtoBuf.ProtoReader.EndSubItem(SubItemToken token, ProtoReader reader) in C:\Code\pb-net_24\src\protobuf-net\ProtoReader.cs:line 618
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type) in C:\Code\pb-net_24\src\protobuf-net\ProtoReader.cs:line 592
   at proto_60(Object, ProtoReader)
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at Vintagestory.API.Util.SerializerUtil.Deserialize[T](Byte[] data)
   at Vintagestory.Server.ServerMapRegion.FromBytes(Byte[] serializedMapRegion)
   at Vintagestory.Server.ServerSystemSupplyChunks.TryLoadMapRegion(Int32 regionX, Int32 regionZ)
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegion(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams)
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegionEnsureNeighbours(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams)
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapChunk(ChunkColumnLoadRequest chunkRequest, Boolean forceCreate)
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn_OnChunkThread(ChunkColumnLoadRequest chunkRequest, Int32 stage)
   at Vintagestory.Server.ServerSystemSupplyChunks.tryLoadOrGenerateChunkColumnsInQueue()
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick()
   at Vintagestory.Server.ServerThread.Update()
   at Vintagestory.Server.ServerThread.Process()
26.3.2024 10:42:46 [Notification] All clients disconnected, pausing game calendar.
26.3.2024 10:42:46 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception during Process
26.3.2024 10:42:46 [Notification] Server ticking has been suspended
26.3.2024 10:42:46 [Notification] Entering runphase Shutdown
26.3.2024 10:42:46 [Notification] Defragmented listener lists
26.3.2024 10:42:46 [Event] Mods and systems notified, now saving everything...
26.3.2024 10:42:46 [Event] Saved player world data...
26.3.2024 10:42:46 [Event] Saved map regions...
26.3.2024 10:42:46 [Event] Saved map chunks...
26.3.2024 10:42:46 [Event] Saved loaded chunks...
26.3.2024 10:42:46 [Event] Saved generating chunks...
26.3.2024 10:42:46 [Event] Saved savegamedata...2
26.3.2024 10:42:46 [Event] World saved! Saved 0 chunks, 0 mapchunks, 0 mapregions.
26.3.2024 10:42:46 [Event] Shutting down 6 server threads... 
26.3.2024 10:42:46 [Event] Killed console thread
26.3.2024 10:42:47 [Event] All threads gracefully shut down
26.3.2024 10:42:47 [Event] Doing last tick...
26.3.2024 10:42:47 [Event] Stopped the server!

**Comment by tyronx** [comment]
starting in repair mode should fix that broken mapchunk

**Comment by tkk2112** [comment]
Sorry I could have said that transferring the save to my windows pc and opening as a singleplayer game in repair mode fixed it. I still have the save if somebody want to debug the actual crash.

**Comment by Craluminum2413** [comment]
Duplicate of #3734
