### ISSUE TITLE
Items like chest after open in boat cargo slot won't stack.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4129]
### Game Version

v1.20 pre2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

All items like chest, storage vessel, crate etc. that you can put in boat cargo slot after use "I mean click for open" will gain "empty" label and thanks to it, you can't stack this same items type because of it.

### How to reproduce

Like on video just place 2 chest on boat and click for open only 1. After it pick it up from boat to your inventory and try stack.

### Screenshots

https://github.com/user-attachments/assets/63f41f43-3760-4125-88b2-61fb615d010e

<img width="690" alt="Vintagestory Screenshot 2024 09 20 - 21 46 18 89" src="https://github.com/user-attachments/assets/97051b3c-09ec-4ece-b8d9-780ebcf573b9">
<img width="590" alt="Vintagestory Screenshot 2024 09 20 - 21 46 26 18" src="https://github.com/user-attachments/assets/73e9091d-450c-42dc-ac77-c3fed3f7f579">
<img width="622" alt="Vintagestory Screenshot 2024 09 20 - 21 51 06 70" src="https://github.com/user-attachments/assets/a8dbec9e-ddf8-45a1-bda0-50c78b5d37b0">
<img width="590" alt="Vintagestory Screenshot 2024 09 20 - 21 51 09 04" src="https://github.com/user-attachments/assets/b594a908-6726-4c77-9f30-6b082693ead9">

### Logs

```Log```

**Comment by Craluminum2413** [comment]
Fixed in pre.6

**Comment by CookieBoy21** [comment]
This bug wasn't fixed. Storage items like chest will still get "empty" label after open it in ship cargo slot. Tested in 1.20 pre.6

**Comment by Craluminum2413** [comment]
@CookieBoy21 But they stack now

**Comment by CookieBoy21** [comment]
Ah okay, they can stack but only "empty" label don't disappear.
