### ISSUE TITLE
Incorrect/confusion name for rice alcohol.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#5075]
### Game Version

1.20.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

In handbook, from rice we can make rice ale and after distillation rice whiskey. But after making it instead of getting rice ale we have sake and after distillation we will get again sake. Weak and strong alcohol, made from rice use this same name.

### How to reproduce

Just check how it look in handbook and check how this look after making it.

### Screenshots

![Image](https://github.com/user-attachments/assets/970e62d0-3f2e-48b0-bff7-e507e5964bc3)

![Image](https://github.com/user-attachments/assets/84943258-2361-4d73-aab7-831bedce355b)

### Logs

```Crash```

**Comment by pizza2004** [comment]
This one is a strange one.  The game treats both as Sake when in containers and as Rice Wine or Rice Ale when not in containers.  Most likely it should have a slight change for consistency.  I'll look into it.

**Comment by RedramVS** [comment]
The reason you see different translation likely has to do with there being separate items of these, and incontainer-items.  Apparently they aren't matching currently.
I believe the intended standard is for rice cider to be sake, and rice spirits to be whiskey.  Google says that sake is something like 22% alcohol or lower.  I believe our spirits are generally in the 40% alcohol range.  So it would appear irl sake is closer to wine than it is to whiskey.

**Comment by RedramVS** [comment]
Should be fixed next update

**Comment by CookieBoy21** [comment]
I think that issue was not fixed. If I good understand after update alcohol made by fermentation should call sake and made by distillation should call rice whiskey. Also there is still difference between how rice alcohol is called in handbook and how it's called after fermentation/distillation when player making it.
