### ISSUE TITLE
Incorrect windmill behavior when two rotors are connected to a toggle

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/VintageStory-Issues#539]
**On the OPTS**

### Description
When two windmill rotors are connected to either side of a helve hammer toggle so that their faces are opposite, one will reverse direction and add torque to the system.

### Screenshots
In the first image, the rotor on the left is rotating counter-clockwise with respect to the toggle. As is the other rotor, even though it should be rotating the other direction.
In the second image, the rotors are rotating the correct directions.

![image](https://user-images.githubusercontent.com/22282562/83970005-227c6480-a8a1-11ea-8077-8bb4d9859e4f.png)
![image](https://user-images.githubusercontent.com/22282562/83970006-24debe80-a8a1-11ea-8876-3ead473e576c.png)

**Comment by radfast** [comment]
Thank you for reporting, this is fixed in upcoming 1.13.

(Preview versions of 1.13, potentially still with a few bugs in the new features, are available in the News channel of the VS Discord.)

**Comment by copygirl** [comment]
Yes, as @radfast points out, the mechanical parts of the game have been worked on quite a bit. If issues persist, please create a new issue outlining them. Also, @VeryGoodDog, please don't forget to include the game version when creating an issue.
