### ISSUE TITLE
Trapped by Treasure Hunter's Bed

### ISSUE THREAD

**Issue by Chil-Phil** [anegostudios/VintageStory-Issues#6115]
### Game Version

v1.21.0-pre.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I stayed the night in the bed to the left of the fireplace at the new Treasure Hunter's hut. When my character woke up in the morning, they were trapped in the roof of the hut, unable to escape. My character remained trapped until they were put out of their misery by the local surface bowtorn. This happens at just about the end of the logs provided if anyone thinks it could help.

### How to reproduce

1. Sleep in the bed at a Treasure Hunter's Hut.
2. Wake up: upper body is stuck in the roof yet exposed to the outside. Since the Treasure Hunter owns the plot, blocks cannot be destroyed, meaning escape is not possible.
3. (optional) get shot by a passing bowtorn to end your misery and respawn.

### Logs (Required)

[server-audit.log](https://github.com/user-attachments/files/20822107/server-audit.log)

[client-audit.log](https://github.com/user-attachments/files/20822116/client-audit.log)

**Comment by sekelsta** [comment]
This was fixed by dilli at some point and no longer occurs in 1.21.0-rc.3

**Comment by LilyInTheWater** [comment]
This is still happening, unfortunately. I'm on 1.22.6 and it happened to me.

**Comment by MKMoose** [comment]
This seems like it was apparently fixed on TOPS, judging by [this discord message](https://discord.com/channels/302152934249070593/1496784145274372116/1536727234071633980). Not sure about how that works with the main version of the game.

> Fixed: getting out of the bed did not check all possilbe spots which could lead to getting stuck inside blocks

**Comment by Th3Dilli** [comment]
This was broken by fixing another issue but is already fixed again in 1.22.7

**Comment by MKMoose** [comment]
This is _not_ fixed in 1.22.7, or at least not entirely - maybe it is fixed on TOPS, at best. I can still _consistently_ get it to occur with the following steps:

1. Create a new world on standard settings.
2. `/tpstoryloc treasurehunter`
3. `/time set 0`
4. Sleep in the bed.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2b86b30b-34d4-42cd-81a0-a4e834511902" />

[client-debug.log](https://github.com/user-attachments/files/32462370/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/32462373/client-main.log)
[server-debug.log](https://github.com/user-attachments/files/32462372/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/32462371/server-main.log)

**Comment by Th3Dilli** [comment]
@MKMoose I am not sure what may be wrong but that fix is included in the public release and not just tops

I just tested again on two new worlds and there it works as expected , could you maybe try reinstalling the game completely?

**Comment by MKMoose** [comment]
@Th3Dilli I did a full reinstall, the issue no longer occurs. Then compiled from the public repos, the issue is back. So the fix is included in the public release, but for some reason isn't present in the public repos despite both claiming they are the same version.

The issue can presumably be marked as resolved, but having code differences between the game and repos is a bit odd to say the least.
