### ISSUE TITLE
Prospecting pick breaks ALL blocks without dropping anything

### ISSUE THREAD

**Issue by RustyPeanuts** [anegostudios/VintageStory-Issues#6187]
### Game Version

v1.20.12

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The prospecting pickaxe's job is to search the area for ore deposits, and when you break a stone block with it, it does not drop anything. I assume this is intentional. However, this behavior of not dropping anything does not apply only to stone blocks. It applies to all blocks -- for instance, I was in a cave today and I broke a loose rusty gear on the cave floor with my prospecting pick (unknowingly) and it dropped nothing. This is likely just an oversight, but I can't imagine the developers would consider this behavior 'intentional'.

### How to reproduce

1. Grab a prospecting pick
2. In density or node search mode (it doesn't matter), break a non-stone block, like a loose rusty gear
3. Observe that the block does NOT drop any items

### Logs (Required)

[client-audit.log](https://github.com/user-attachments/files/20994794/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/20994790/client-chat.log)
[client-debug.log](https://github.com/user-attachments/files/20994792/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/20994791/client-main.log)
[server-audit.log](https://github.com/user-attachments/files/20994788/server-audit.log)
[server-build.log](https://github.com/user-attachments/files/20994795/server-build.log)
[server-chat.log](https://github.com/user-attachments/files/20994789/server-chat.log)
[server-debug.log](https://github.com/user-attachments/files/20994793/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/20994796/server-main.log)

**Comment by zand** [comment]
I do agree that the prospecting pick not dropping anything does seem intentional, but I feel that the reasoning seems lost. In general, the prospecting pick, not flooding the player's inventory with stones, is more of a reward than a punishment by the time you obtain it. It does punish players who try to use it to mine ore, but it wouldn't stop a player from breaking the blocks around an ore block in order to obtain it that way. The idea of the blocks fully breaking from taking small samples is probably what is wrong.

I would probably recommend that the prospecting pick be given a low random chance of braking a block while dropping items when it finally breaks.

**Comment by pizza2004** [comment]
Fixed in 1.22.

**Comment by MKMoose** [comment]
The issue still partially persists in 1.22 (as of 1.22.3), because what was resolved (if anything - I haven't compared exactly) was just decorative blocks not dropping, whereas all blocks which have the `Ore` or `Stone` material (e.g. cobblestone, quern) but don't produce a reading still don't drop when broken.

Seems like it can be trivially addressed by removing the material check and using the same `ItemProspectingPick.isPropickable()` condition which determines whether a block can produce a reading.

I can't help but also mention that a chunk of the code there is duplicated in `ItemProspectingPick.ProbeBlockNodeMode()` and `ItemProspectingPick.ProbeBlockDensityMode()`, and seems like it can be safely moved to `ItemProspectingPick.OnBlockBrokenWith()`.

**Comment by RustyPeanuts** [comment]
@Craluminum2413 @MKMoose @pizza2004 @Lazula
This issue is not entirely fixed as of 1.22.6, and MKMoose did a great job of explaining why. **Read his comment.** Blocks like cobblestone and loose stones are still broken because they are part of the "Stone" or "Ore" material group. **Please reopen the issue and fix!**
