### ISSUE TITLE
After update to 1.21.2 labeled chests does not show texts at labels

### ISSUE THREAD

**Issue by fipil** [anegostudios/VintageStory-Issues#7251]
### Game Version

1.21.2

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

After update our server to the 1.21.2, we noticed that the text on the labeled chests is not visible. If I try to edit the text with charcoal, it's there. So problem is only with showing.
We've modded server, but I tried it on vanilla as well, see below.

### How to reproduce

1. Place labeled chest and write a text to the label. 
2. Text is not shown.

Second attempt:

1. I also tried to create a new world in the 1.21.1 version and put there some labeled chests with texts.
2. Loaded the world into the 1.21.2.
3. Text is not visible. Same as on our server.

### Logs (Required)

[client-main.log](https://github.com/user-attachments/files/22716684/client-main.log)
[server-main.log](https://github.com/user-attachments/files/22716683/server-main.log)
[server-debug.log](https://github.com/user-attachments/files/22716685/server-debug.log)

**Comment by radfast** [comment]
Thanks for reporting, this is a known issue - please see [devlog](https://www.vintagestory.at/blog.html/news/v1212-story-chapter-2-redux-tops-lagspike-patch-r427/)

We are aiming to have this fixed in a version 1.21.3 as soon as possible, maybe even today

**Comment by qwackywacky** [comment]
Currently on 1.21.4 and still having this issue
Chests with signs don't show text but normal signs do
